### ISSUE TITLE
[Feature Request] "open_with_Item"Menu access via handheld item click

### ISSUE THREAD

**Issue by CatBang** [HelpChat/DeluxeMenus#135]
# Open this menu by clicking a specific item

  open_with_Item:
    material: clock      # Define the item that will be clicked
    left-click: false      #Left-click to open the menu while holding this item
    right-click: true      #Right-click to open the menu while holding this item

Usage scenario: Bind an item to open the menu; when holding this item, both left and right clicks will open the menu interface without the need to rely on other plugins to enter commands to open the menu.

**Comment by CatBang** [comment]
Many menu plugins have this feature, but currently DeluxeMenus lacks the ability to open the menu with a handheld item click, which relies on third-party plugins. It is indeed not quite appropriate, and it is hoped that this feature can be added.❤️

**Comment by BlitzOffline** [comment]
Hello,

We understand why people want this feature and we've had it requested a few times but we've always refused to implement it. The reason is fairly simple: people have very different expectations from a feature like this (some want items to be permanent in people's inventories, some don't want, some want the items to execute all sorts of actions not just opening menus, some want the items to be consumable, etc.). Unfortunately, we don't have enough development time to implement and maintain all these features. For this reason, we will always refer people to using other plugins that do exactly what they need and also have developers spending full time developing and maintaining.

One plugin I've suggested for a long time is [ItemJoin](https://www.spigotmc.org/resources/itemjoin.12661/) simply because it is what I used for a long time and it just worked.

Thank you for your understanding!

**Comment by CatBang** [comment]
> Hello,
> 
> We understand why people want this feature and we've had it requested a few times but we've always refused to implement it. The reason is fairly simple: people have very different expectations from a feature like this (some want items to be permanent in people's inventories, some don't want, some want the items to execute all sorts of actions not just opening menus, some want the items to be consumable, etc.). Unfortunately, we don't have enough development time to implement and maintain all these features. For this reason, we will always refer people to using other plugins that do exactly what they need and also have developers spending full time developing and maintaining.
> 
> One plugin I've suggested for a long time is [ItemJoin](https://www.spigotmc.org/resources/itemjoin.12661/) simply because it is what I used for a long time and it just worked.
> 
> Thank you for your understanding!

Alright, I'm sorry that this is your final decision😔. In fact, I believe that most people just need this simple feature: the ability to open a menu by clicking on an item they are holding. "Itemjoin" might be fantastic, but many people simply do not need the additional features it brings in most situations. My thought is to minimize the number of unnecessary plugins as much as possible, which aligns with your idea of avoiding the addition of unnecessary features, I understand.🪻
