### ISSUE TITLE
Strange bug with placeholders and command arguments

### ISSUE THREAD

**Issue by Limeen** [HelpChat/DeluxeMenus#136]
I recently discovered a strange bug with the ``%parseother_{<player>}_{<placeholder_without_percent}%`` placeholder

The plugin does not take into account my ``<target>`` argument when I do the command ``/p <target>``
but only in placeholders, on text I can write
Username: ``{target}``
but I can not do
Username: ``%parseother_{{target}}_{player_name}%``

**Video demo:**
https://github.com/user-attachments/assets/01c2d1b4-753b-49f4-a490-e8e8dcaefb1b

**Infos:**
Server version: ``Purpur (Paper) 1.21.1``
DeluxeMenus version: ``1.14.1-DEV-184``
Placeholders api version: ``2.11.7-DEV-200``

**Comment by BlitzOffline** [comment]
Hello. This issue seems to be related to the following issue: https://github.com/HelpChat/DeluxeMenus/issues/78. An easy fix would be to add the option `parse_placeholders_after_arguments: true` to the menus you want to fix this issue in.

**PLEASE**, read the message in https://github.com/HelpChat/DeluxeMenus/pull/99 to understand exactly what this change means. There are some security reason for which it was made. Also, if this change doesn't fix your issue or you have any other questions, please reopen this issue.

**Comment by BlitzOffline** [comment]
> Thanks! maybe adding that to the documentation would be great

We usually do that after or slightly before the Spigot release.
