### ISSUE TITLE
Armor Trims

### ISSUE THREAD

**Issue by TopStrixStudios** [HelpChat/DeluxeMenus#55]
Add an option to add trim upgrades to armor, thanks.

**Comment by TopStrixStudios** [comment]
hey, any updates ?

**Comment by TopStrixStudios** [comment]
up

**Comment by BlitzOffline** [comment]
Hello @TopStrixStudios. It has been a while since you've requested this but I finally got around to doing it. 

If you want to test a build, you can get it here (remember to extract the jar file from the zip file): 
[DeluxeMenus-1.14.1-DEV-local-build.zip](https://github.com/HelpChat/DeluxeMenus/files/14763447/DeluxeMenus-1.14.1-DEV-local-build.zip)

This is built on top of the latest Development Build released on Jenkins: https://ci.extendedclip.com/job/DeluxeMenus/lastSuccessfulBuild/

You can use the options:
- `trim_material`: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/meta/trim/TrimMaterial.html
- `trim_pattern`: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/meta/trim/TrimPattern.html
