### ISSUE TITLE
add action title and subtitle

### ISSUE THREAD

**Issue by Playsus1234** [HelpChat/DeluxeMenus#96]
add action title and subtitle

**Comment by BlitzOffline** [comment]
Hello. We have not added these features as built-in actions, because we believe the already existent `/minecraft:title` command is better than anything we could offer.

If you do not know how to use the command, you can find the documentation here: https://www.digminecraft.com/game_commands/title_command.php
You can also find a nice user interface to help you generate title commands here: https://minecraft.tools/en/title.php

If you have good arguments for adding these as built-in actions, please reopen the issue or create another one and share those arguments. Thank You!
